replicaCount: 2

image:
  repository: "" # יתעדכן אוטומטית על ידי ה-Pipeline של GitHub Actions עם ה-ECR URL
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi