apiVersion: v1
kind: Service
metadata:
  name: AWS-EKS-Flask-Deployment-app-service
  labels:
    app: AWS-EKS-Flask-Deployment-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: AWS-EKS-Flask-Deployment-app